# Generated by Django 4.1 on 2022-09-17 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(default='', max_length=100, unique=True)),
                ('nickname', models.CharField(default='', max_length=100, unique=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Portfolio_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio_name', models.CharField(max_length=50, unique=True)),
                ('strategy_number', models.CharField(max_length=100)),
                ('start_date', models.CharField(max_length=100)),
                ('end_date', models.CharField(max_length=100)),
                ('rebalancing_duration', models.CharField(max_length=100)),
                ('input_money', models.CharField(max_length=100)),
                ('input_way', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_id', models.CharField(default='0', max_length=100)),
                ('first_group', models.CharField(max_length=100)),
                ('second_group', models.CharField(max_length=100)),
                ('third_group', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(default='0', max_length=1000)),
                ('rate', models.CharField(blank=True, max_length=100, null=True)),
                ('upper', models.CharField(blank=True, max_length=30, null=True)),
                ('lower', models.CharField(blank=True, max_length=30, null=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolio_info')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio_result_temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipt_money', models.CharField(max_length=100)),
                ('recipt_period', models.CharField(max_length=100)),
                ('logic_info', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolio_info')),
            ],
        ),
    ]
