# Generated by Django 4.1 on 2022-09-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_info',
            name='lower',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='product_info',
            name='upper',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
