# Generated by Django 4.1 on 2022-09-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_product_info_lower_product_info_upper'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_info',
            old_name='detail',
            new_name='name',
        ),
        migrations.AddField(
            model_name='product_info',
            name='number',
            field=models.CharField(default='0', max_length=1000),
        ),
    ]
