# Generated by Django 4.1 on 2022-09-17 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_rename_detail_product_info_name_product_info_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_info',
            name='temp_id',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
